server:
  port: 9039
  
spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration 
  datasource:
    url: ${url}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate: 
      ddl-auto: none


document:
  bucket-name: ${bucket_name}
cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: ${S3_access_key}
      secret-key: ${S3_secret_key}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
